#############################################################################
# Makefile for building: AGV_Calling_device
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 5? 20 18:58:27 2017
# Project:  AGV_Calling_device.pro
# Template: app
# Command: /opt/qt-m6g2c/bin/qmake -spec /opt/qt-m6g2c/mkspecs/qws/linux-arm-gnueabi-g++ -o Makefile AGV_Calling_device.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc -lts
CXX           = arm-linux-gnueabihf-g++ -lts
DEFINES       = -DQEXTSERIALPORT_USING_SHARED -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-m6g2c/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I/opt/qt-m6g2c/include/QtCore -I/opt/qt-m6g2c/include/QtNetwork -I/opt/qt-m6g2c/include/QtGui -I/opt/qt-m6g2c/include -I. -I/opt/qt-m6g2c/include/QtExtSerialPort -I. -I/opt/tslib/include
LINK          = arm-linux-gnueabihf-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-m6g2c/lib
LIBS          = $(SUBLIBS)  -L/opt/tslib/lib -L/opt/qt-m6g2c/lib -lqextserialport -lQtGui -L/opt/tslib/lib -L/opt/qt-m6g2c/lib -lQtNetwork -lQtCore -lrt -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-m6g2c/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = configdialog.cpp \
		main.cpp \
		qextserial.cpp \
		widget.cpp \
		workstation.cpp moc_configdialog.cpp \
		moc_qextserial.cpp \
		moc_widget.cpp \
		moc_workstation.cpp \
		qrc_rc.cpp
OBJECTS       = configdialog.o \
		main.o \
		qextserial.o \
		widget.o \
		workstation.o \
		moc_configdialog.o \
		moc_qextserial.o \
		moc_widget.o \
		moc_workstation.o \
		qrc_rc.o
DIST          = /opt/qt-m6g2c/mkspecs/common/unix.conf \
		/opt/qt-m6g2c/mkspecs/common/linux.conf \
		/opt/qt-m6g2c/mkspecs/common/gcc-base.conf \
		/opt/qt-m6g2c/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-m6g2c/mkspecs/common/g++-base.conf \
		/opt/qt-m6g2c/mkspecs/common/g++-unix.conf \
		/opt/qt-m6g2c/mkspecs/common/qws.conf \
		/opt/qt-m6g2c/mkspecs/qconfig.pri \
		/opt/qt-m6g2c/mkspecs/features/qt_functions.prf \
		/opt/qt-m6g2c/mkspecs/features/qt_config.prf \
		/opt/qt-m6g2c/mkspecs/features/exclusive_builds.prf \
		/opt/qt-m6g2c/mkspecs/features/default_pre.prf \
		/opt/qt-m6g2c/mkspecs/features/release.prf \
		/opt/qt-m6g2c/mkspecs/features/default_post.prf \
		/opt/qt-m6g2c/mkspecs/features/extserialport.prf \
		/opt/qt-m6g2c/mkspecs/features/shared.prf \
		/opt/qt-m6g2c/mkspecs/features/warn_on.prf \
		/opt/qt-m6g2c/mkspecs/features/qt.prf \
		/opt/qt-m6g2c/mkspecs/features/unix/thread.prf \
		/opt/qt-m6g2c/mkspecs/features/moc.prf \
		/opt/qt-m6g2c/mkspecs/features/resources.prf \
		/opt/qt-m6g2c/mkspecs/features/uic.prf \
		/opt/qt-m6g2c/mkspecs/features/yacc.prf \
		/opt/qt-m6g2c/mkspecs/features/lex.prf \
		/opt/qt-m6g2c/mkspecs/features/include_source_dir.prf \
		AGV_Calling_device.pro
QMAKE_TARGET  = AGV_Calling_device
DESTDIR       = 
TARGET        = AGV_Calling_device

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AGV_Calling_device.pro  /opt/qt-m6g2c/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf /opt/qt-m6g2c/mkspecs/common/unix.conf \
		/opt/qt-m6g2c/mkspecs/common/linux.conf \
		/opt/qt-m6g2c/mkspecs/common/gcc-base.conf \
		/opt/qt-m6g2c/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-m6g2c/mkspecs/common/g++-base.conf \
		/opt/qt-m6g2c/mkspecs/common/g++-unix.conf \
		/opt/qt-m6g2c/mkspecs/common/qws.conf \
		/opt/qt-m6g2c/mkspecs/qconfig.pri \
		/opt/qt-m6g2c/mkspecs/features/qt_functions.prf \
		/opt/qt-m6g2c/mkspecs/features/qt_config.prf \
		/opt/qt-m6g2c/mkspecs/features/exclusive_builds.prf \
		/opt/qt-m6g2c/mkspecs/features/default_pre.prf \
		/opt/qt-m6g2c/mkspecs/features/release.prf \
		/opt/qt-m6g2c/mkspecs/features/default_post.prf \
		/opt/qt-m6g2c/mkspecs/features/extserialport.prf \
		/opt/qt-m6g2c/mkspecs/features/shared.prf \
		/opt/qt-m6g2c/mkspecs/features/warn_on.prf \
		/opt/qt-m6g2c/mkspecs/features/qt.prf \
		/opt/qt-m6g2c/mkspecs/features/unix/thread.prf \
		/opt/qt-m6g2c/mkspecs/features/moc.prf \
		/opt/qt-m6g2c/mkspecs/features/resources.prf \
		/opt/qt-m6g2c/mkspecs/features/uic.prf \
		/opt/qt-m6g2c/mkspecs/features/yacc.prf \
		/opt/qt-m6g2c/mkspecs/features/lex.prf \
		/opt/qt-m6g2c/mkspecs/features/include_source_dir.prf \
		/opt/qt-m6g2c/lib/libqextserialport.prl \
		/opt/qt-m6g2c/lib/libQtGui.prl \
		/opt/qt-m6g2c/lib/libQtNetwork.prl \
		/opt/qt-m6g2c/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qt-m6g2c/mkspecs/qws/linux-arm-gnueabi-g++ -o Makefile AGV_Calling_device.pro
/opt/qt-m6g2c/mkspecs/common/unix.conf:
/opt/qt-m6g2c/mkspecs/common/linux.conf:
/opt/qt-m6g2c/mkspecs/common/gcc-base.conf:
/opt/qt-m6g2c/mkspecs/common/gcc-base-unix.conf:
/opt/qt-m6g2c/mkspecs/common/g++-base.conf:
/opt/qt-m6g2c/mkspecs/common/g++-unix.conf:
/opt/qt-m6g2c/mkspecs/common/qws.conf:
/opt/qt-m6g2c/mkspecs/qconfig.pri:
/opt/qt-m6g2c/mkspecs/features/qt_functions.prf:
/opt/qt-m6g2c/mkspecs/features/qt_config.prf:
/opt/qt-m6g2c/mkspecs/features/exclusive_builds.prf:
/opt/qt-m6g2c/mkspecs/features/default_pre.prf:
/opt/qt-m6g2c/mkspecs/features/release.prf:
/opt/qt-m6g2c/mkspecs/features/default_post.prf:
/opt/qt-m6g2c/mkspecs/features/extserialport.prf:
/opt/qt-m6g2c/mkspecs/features/shared.prf:
/opt/qt-m6g2c/mkspecs/features/warn_on.prf:
/opt/qt-m6g2c/mkspecs/features/qt.prf:
/opt/qt-m6g2c/mkspecs/features/unix/thread.prf:
/opt/qt-m6g2c/mkspecs/features/moc.prf:
/opt/qt-m6g2c/mkspecs/features/resources.prf:
/opt/qt-m6g2c/mkspecs/features/uic.prf:
/opt/qt-m6g2c/mkspecs/features/yacc.prf:
/opt/qt-m6g2c/mkspecs/features/lex.prf:
/opt/qt-m6g2c/mkspecs/features/include_source_dir.prf:
/opt/qt-m6g2c/lib/libqextserialport.prl:
/opt/qt-m6g2c/lib/libQtGui.prl:
/opt/qt-m6g2c/lib/libQtNetwork.prl:
/opt/qt-m6g2c/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qt-m6g2c/mkspecs/qws/linux-arm-gnueabi-g++ -o Makefile AGV_Calling_device.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/AGV_Calling_device1.0.0 || $(MKDIR) .tmp/AGV_Calling_device1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/AGV_Calling_device1.0.0/ && $(COPY_FILE) --parents configdialog.h qextserial.h widget.h workstation.h .tmp/AGV_Calling_device1.0.0/ && $(COPY_FILE) --parents rc.qrc .tmp/AGV_Calling_device1.0.0/ && $(COPY_FILE) --parents configdialog.cpp main.cpp qextserial.cpp widget.cpp workstation.cpp .tmp/AGV_Calling_device1.0.0/ && (cd `dirname .tmp/AGV_Calling_device1.0.0` && $(TAR) AGV_Calling_device1.0.0.tar AGV_Calling_device1.0.0 && $(COMPRESS) AGV_Calling_device1.0.0.tar) && $(MOVE) `dirname .tmp/AGV_Calling_device1.0.0`/AGV_Calling_device1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/AGV_Calling_device1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_configdialog.cpp moc_qextserial.cpp moc_widget.cpp moc_workstation.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_configdialog.cpp moc_qextserial.cpp moc_widget.cpp moc_workstation.cpp
moc_configdialog.cpp: configdialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) configdialog.h -o moc_configdialog.cpp

moc_qextserial.cpp: qextserial.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) qextserial.h -o moc_qextserial.cpp

moc_widget.cpp: workstation.h \
		qextserial.h \
		widget.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_workstation.cpp: qextserial.h \
		workstation.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) workstation.h -o moc_workstation.cpp

compiler_rcc_make_all: qrc_rc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rc.cpp
qrc_rc.cpp: rc.qrc \
		image/light_bulb.png \
		image/OK.png \
		image/subway_status_118px_1118816_easyicon.net.png \
		image/calling.png \
		image/PNG114.png \
		image/PNG102.png \
		image/arrow_left.png \
		image/telephone.png \
		image/error.png
	/opt/qt-m6g2c/bin/rcc -name rc rc.qrc -o qrc_rc.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

configdialog.o: configdialog.cpp configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialog.o configdialog.cpp

main.o: main.cpp widget.h \
		workstation.h \
		qextserial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qextserial.o: qextserial.cpp qextserial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserial.o qextserial.cpp

widget.o: widget.cpp widget.h \
		workstation.h \
		qextserial.h \
		configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

workstation.o: workstation.cpp workstation.h \
		qextserial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workstation.o workstation.cpp

moc_configdialog.o: moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialog.o moc_configdialog.cpp

moc_qextserial.o: moc_qextserial.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserial.o moc_qextserial.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_workstation.o: moc_workstation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_workstation.o moc_workstation.cpp

qrc_rc.o: qrc_rc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rc.o qrc_rc.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

